{"uuid": "abeb2638-feae-429b-951f-f9397945e861", "children": ["8482c9bc-6241-441f-9772-1d4ea23ef5da"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable\n\n", "trace": "  File \"/home/mkorytko/.local/lib/python3.10/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/home/mkorytko/.local/lib/python3.10/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/home/mkorytko/.local/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/home/mkorytko/.local/lib/python3.10/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/mkorytko/.local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1196, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/mkorytko/.local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 923, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/mkorytko/Desktop/Sprint_6-develop/conftest.py\", line 11, in driver\n    driver = webdriver.Firefox()\n  File \"/home/mkorytko/.local/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py\", line 72, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/home/mkorytko/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 263, in __init__\n    self.start_session(capabilities)\n  File \"/home/mkorytko/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 366, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/home/mkorytko/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 458, in execute\n    self.error_handler.check_response(response)\n  File \"/home/mkorytko/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1757436080798, "stop": 1757436081329}], "start": 1757436080798, "stop": 1757436081400}